/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/kubernetes-csi/external-snapshotter/pkg/apis/volumesnapshot/v1"
	scheme "github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SnapshotClassesGetter has a method to return a SnapshotClassInterface.
// A group's client should implement this interface.
type SnapshotClassesGetter interface {
	SnapshotClasses() SnapshotClassInterface
}

// SnapshotClassInterface has methods to work with SnapshotClass resources.
type SnapshotClassInterface interface {
	Create(*v1.SnapshotClass) (*v1.SnapshotClass, error)
	Update(*v1.SnapshotClass) (*v1.SnapshotClass, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.SnapshotClass, error)
	List(opts metav1.ListOptions) (*v1.SnapshotClassList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SnapshotClass, err error)
	SnapshotClassExpansion
}

// snapshotClasses implements SnapshotClassInterface
type snapshotClasses struct {
	client rest.Interface
}

// newSnapshotClasses returns a SnapshotClasses
func newSnapshotClasses(c *VolumesnapshotV1Client) *snapshotClasses {
	return &snapshotClasses{
		client: c.RESTClient(),
	}
}

// Get takes name of the snapshotClass, and returns the corresponding snapshotClass object, and an error if there is any.
func (c *snapshotClasses) Get(name string, options metav1.GetOptions) (result *v1.SnapshotClass, err error) {
	result = &v1.SnapshotClass{}
	err = c.client.Get().
		Resource("snapshotclasses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SnapshotClasses that match those selectors.
func (c *snapshotClasses) List(opts metav1.ListOptions) (result *v1.SnapshotClassList, err error) {
	result = &v1.SnapshotClassList{}
	err = c.client.Get().
		Resource("snapshotclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested snapshotClasses.
func (c *snapshotClasses) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("snapshotclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a snapshotClass and creates it.  Returns the server's representation of the snapshotClass, and an error, if there is any.
func (c *snapshotClasses) Create(snapshotClass *v1.SnapshotClass) (result *v1.SnapshotClass, err error) {
	result = &v1.SnapshotClass{}
	err = c.client.Post().
		Resource("snapshotclasses").
		Body(snapshotClass).
		Do().
		Into(result)
	return
}

// Update takes the representation of a snapshotClass and updates it. Returns the server's representation of the snapshotClass, and an error, if there is any.
func (c *snapshotClasses) Update(snapshotClass *v1.SnapshotClass) (result *v1.SnapshotClass, err error) {
	result = &v1.SnapshotClass{}
	err = c.client.Put().
		Resource("snapshotclasses").
		Name(snapshotClass.Name).
		Body(snapshotClass).
		Do().
		Into(result)
	return
}

// Delete takes name of the snapshotClass and deletes it. Returns an error if one occurs.
func (c *snapshotClasses) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("snapshotclasses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *snapshotClasses) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Resource("snapshotclasses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched snapshotClass.
func (c *snapshotClasses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SnapshotClass, err error) {
	result = &v1.SnapshotClass{}
	err = c.client.Patch(pt).
		Resource("snapshotclasses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
