/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubernetes-csi/external-snapshotter/pkg/apis/volumesnapshot/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSnapshotClasses implements SnapshotClassInterface
type FakeSnapshotClasses struct {
	Fake *FakeVolumesnapshotV1alpha1
}

var snapshotclassesResource = schema.GroupVersionResource{Group: "volumesnapshot", Version: "v1alpha1", Resource: "snapshotclasses"}

var snapshotclassesKind = schema.GroupVersionKind{Group: "volumesnapshot", Version: "v1alpha1", Kind: "SnapshotClass"}

// Get takes name of the snapshotClass, and returns the corresponding snapshotClass object, and an error if there is any.
func (c *FakeSnapshotClasses) Get(name string, options v1.GetOptions) (result *v1alpha1.SnapshotClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(snapshotclassesResource, name), &v1alpha1.SnapshotClass{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotClass), err
}

// List takes label and field selectors, and returns the list of SnapshotClasses that match those selectors.
func (c *FakeSnapshotClasses) List(opts v1.ListOptions) (result *v1alpha1.SnapshotClassList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(snapshotclassesResource, snapshotclassesKind, opts), &v1alpha1.SnapshotClassList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SnapshotClassList{ListMeta: obj.(*v1alpha1.SnapshotClassList).ListMeta}
	for _, item := range obj.(*v1alpha1.SnapshotClassList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested snapshotClasses.
func (c *FakeSnapshotClasses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(snapshotclassesResource, opts))
}

// Create takes the representation of a snapshotClass and creates it.  Returns the server's representation of the snapshotClass, and an error, if there is any.
func (c *FakeSnapshotClasses) Create(snapshotClass *v1alpha1.SnapshotClass) (result *v1alpha1.SnapshotClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(snapshotclassesResource, snapshotClass), &v1alpha1.SnapshotClass{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotClass), err
}

// Update takes the representation of a snapshotClass and updates it. Returns the server's representation of the snapshotClass, and an error, if there is any.
func (c *FakeSnapshotClasses) Update(snapshotClass *v1alpha1.SnapshotClass) (result *v1alpha1.SnapshotClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(snapshotclassesResource, snapshotClass), &v1alpha1.SnapshotClass{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotClass), err
}

// Delete takes name of the snapshotClass and deletes it. Returns an error if one occurs.
func (c *FakeSnapshotClasses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(snapshotclassesResource, name), &v1alpha1.SnapshotClass{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSnapshotClasses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(snapshotclassesResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SnapshotClassList{})
	return err
}

// Patch applies the patch and returns the patched snapshotClass.
func (c *FakeSnapshotClasses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SnapshotClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(snapshotclassesResource, name, data, subresources...), &v1alpha1.SnapshotClass{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotClass), err
}
